# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_auto_20151207_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingest',
            name='message',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
