# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0002_auto_20151214_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='typ',
            field=models.CharField(choices=[('D', 'Deposit'), ('W', 'Withdrawal')], default='W', max_length=1),
            preserve_default=False,
        ),
    ]
