# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20151211_1406'),
        ('forecasting', '0003_scheduledtransaction_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtransaction',
            name='match',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Transaction'),
        ),
    ]
