# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-27 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0004_scheduledtransaction_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='match',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Transaction'),
        ),
    ]
