# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forecasting', '0006_scheduledtransaction_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledtransaction',
            name='match',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Transaction'),
        ),
    ]
