# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 16:59
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_available', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('balance_current', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('institution_type', models.CharField(max_length=50)),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=255)),
                ('plaid_id', models.CharField(max_length=50)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
                ('typ', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaidAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaid_access_token', models.CharField(max_length=50)),
                ('plaid_public_token', models.CharField(max_length=50)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', django.contrib.postgres.fields.jsonb.JSONField()),
                ('category_id', models.CharField(max_length=50, null=True)),
                ('date', models.DateField()),
                ('meta', django.contrib.postgres.fields.jsonb.JSONField()),
                ('name', models.CharField(max_length=255)),
                ('pending', models.BooleanField()),
                ('plaid_id', models.CharField(max_length=50)),
                ('raw', django.contrib.postgres.fields.jsonb.JSONField()),
                ('score', django.contrib.postgres.fields.jsonb.JSONField()),
                ('typ', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Account')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.PlaidAccount'),
        ),
    ]
