# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plaidaccount',
            old_name='plaid_access_token',
            new_name='access_token',
        ),
        migrations.RenameField(
            model_name='plaidaccount',
            old_name='plaid_public_token',
            new_name='public_token',
        ),
    ]
