# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-23 02:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='pending_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Transaction'),
        ),
    ]
