# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-04 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20151204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidaccount',
            name='access_token',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='public_token',
            field=models.CharField(max_length=200),
        ),
    ]
