# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 19:06
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20151204_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plaidaccount',
            name='public_token',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='raw',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='plaidaccount',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
