# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 19:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20151227_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='pending_transaction',
        ),
    ]
