# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_transaction_pending_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='custom_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
