# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20161219_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='plaid_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
