# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 01:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20161219_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='balance_available',
        ),
        migrations.RemoveField(
            model_name='account',
            name='balance_current',
        ),
    ]
