# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20161219_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='awaiting_import',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='pending',
            field=models.BooleanField(default=False),
        ),
    ]
